name: commit practice

on:
  workflow_dispatch:
    inputs:
      botCommit:
        description: "commit by bot"
        required: true
        default: false
        type: boolean
  push:

jobs:
  autoCommit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Commit changes
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: |
          if [ "${{ github.event.inputs.botCommit }}" == "true" ]; then
            echo "Committing changes as bot"
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit --allow-empty -m "Auto commit by github-actions[bot]"
          else
            echo "Committing changes as user"
            git config --global user.name "${{ github.actor }}"
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            git add .
            git commit --allow-empty -m "Auto commit by ${{ github.actor }}"
          fi

          git push
