name: VRT

on:
  deployment_status:

jobs:
  screenshots:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'Preview'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read

    container:
      image: mcr.microsoft.com/playwright:v1.40.1-focal

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - uses: npm/action-setup@v2
        with:
          version: 8.9.2
          run_install: false
      - name: Get npm store directory
        id: npm-cache
        run: echo "STORE_PATH=$(npm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup npm cache
        with:
          path: ${{ steps.npm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-npm-store-${{ hashFiles('**/npm-lock.yaml') }}-setup-npm
          restore-keys: |
            ${{ runner.os }}-npm-store-setup-npm
      - run: npm install
        shell: bash
      - run: npm test:vrt:screenshots
        env:
          BASE_URL: https://insert-practice.vercel.app/
      - run: npm test:vrt:compare
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
      - name: Upload failed screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: vrt-failed-screenshots-${{ github.sha }}
          path: test-results
